name: 'Pull Request Title Check'
description: 'Validates pull request titles against a configurable regex pattern'

inputs:
  title-pattern:
    description: 'Regex pattern to validate PR title format'
    required: true
    default: '^FIX JIRA-\\d+: .+$'
  expected-format:
    description: 'Description of the expected format for error messages'
    required: true
    default: 'FIX JIRA-123: Subject'
  error-message:
    description: 'Custom error message to display when validation fails'
    required: false
    default: 'Pull request title does not match required format'
  success-message:
    description: 'Custom success message to display when validation passes'
    required: false
    default: 'Pull request title format is correct!'

runs:
  using: 'composite'
  steps:
    - name: Check PR Title Format
      shell: python
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
        TITLE_PATTERN: ${{ inputs.title-pattern }}
        EXPECTED_FORMAT: ${{ inputs.expected-format }}
        ERROR_MESSAGE: ${{ inputs.error-message }}
        SUCCESS_MESSAGE: ${{ inputs.success-message }}
      run: |
        import sys
        import os
        sys.path.append(os.path.dirname(__file__))
        from check_title import main
        main() 