[tool.poetry]
name = "python-example-cloudformation"
authors = ["Ivo Dlouhy"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
aws-lambda-powertools = "^3.14.0"
aws-xray-sdk = "^2.14.0"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
