name: Pull Request Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    uses: ./.github/workflows/reusable-pr-title-check.yml
    with:
      title-pattern: '^FIX JIRA-\\d+: .+$'
      expected-format: 'FIX JIRA-123: Subject'
      error-message: 'Pull request title does not match required format'
      success-message: 'Pull request title format is correct!' 